const URL = "https://momentum-poster-s3.s3.ap-south-1.amazonaws.com/data.json";

let cache = null;
let cacheTime = 0;

const getEvents = async () => {
  // Cache for one minute
  let cacheTimeDiffSec = (Date.now() - cacheTime) / 1000;
  if (cache != null && cacheTimeDiffSec < 60) return cache;

  // const res = await fetch(URL, {
  //   method: "GET",
  //   headers: {
  //     "Content-type": "application/json;charset=UTF-8",
  //   },
  // });
  //const eventList = await res.json();

  const eventList = [
    {
      id: 0,
      name: "IKTAARA",
      shortDesc: "Solo Singing",
      eventType: "ONSTAGE",
      amount: 350,
      teamSizeMin: 1,
      teamSizeMax: 1,
      desc: "Elevate the stage with your local brilliance and connect with the like minds, inviting all the melody maniacs to the solo-singing competition “IKTAARA”",
      rules: "# Songs must be in Hindi/English.\n# Rap portions or refrains are not permissible.\n# Allowed to play an accompanying instrument themselves or can take the help of their friend.\n# The decision of the judges shall be final and binding.\n# Obscenity (at the discretion of judges) of any kind is not allowed and will lead to immediate disqualification.\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Comprises of two rounds: prelims(2minutes) and final(3-3.5minutes)\n# No backing vocals are allowed",
      whatsappLink: "https://chat.whatsapp.com/EFX28OfjwMU2hXu2JtFldb",
      categories: "Music,Non-Technical,Entertainment",
      isRegOpen: true
    },
    {
      "id": 1,
      "name": "GOONJ",
      "shortDesc": "Group Singing",
      "eventType": "ONSTAGE",
      "amount": 1000,
      "teamSizeMin": 5,
      "teamSizeMax": 20,
      "desc": "Join the melodious fun at our college fest's group singing event showcase and celebrate the harmony of talent",
      "rules": "# Maximum two accompanists are allowed.\n# The language must be only English and/or Hindi.\n# The team may sing more than one song within the time limit.\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Participation: There should not be any common members.\n# There will be only one round.\n# Time limit: 10 minutes (including sound check).",
      "whatsappLink": "https://chat.whatsapp.com/HnsBM1UONyL848pjXe1hym",
      "categories": "Music,Non-Technical,Entertainment",
      "isRegOpen": true
    },
    {
      "id": 2,
      "name": "RAGNA-ROCK",
      "amount": 1000,
      "shortDesc": "BATTLE OF BANDS",
      "eventType": "ONSTAGE",
      "teamSizeMin": 5,
      "teamSizeMax": 15,
      "desc": "Experience the battle of the bands like never before at our college fest's electrifying music competition",
      "rules": "# Maximum two accompanists are allowed.\n# The language must be only English and/or Hindi.\n# The team may sing more than one song within the time limit.\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Participation: There should not be any common members.\n# There will be only one round.\n# Time limit: 10 minutes (including sound check).",
      "whatsappLink": "",
      "categories": "Music,Non-Technical,Entertainment",
      "isRegOpen": true
    },
    {
      "id": 3,
      "name": "MIC-DROP",
      "amount": 350,
      "shortDesc": "SOLO RAP",
      "eventType": "ONSTAGE",
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Bring your rhymes to life and own the mic",
      "rules": "# The language of rap must be only English and/or Hindi.\n# The participant is allowed to use puns, double entendres and quips, but any sort of racist, sexist or offensive slurs will lead to immediate disqualification.\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Comprises of two rounds: prelims and final\n# Participants will have a performance of 2 minute. \n# Profanity, swears and sexual slangs (at the judge’s discretion) in the rap are not permitted. Else the participant shall be immediately disqualified. \n# The participants are free to play any beat of their choice.",
      "whatsappLink": "",
      "categories": "Music,Non-Technical,Entertainment",
      "isRegOpen": true
    },
    {
      "id": 4,
      "name": "TARANG",
      "amount": 350,
      "shortDesc": "SOLO DANCE",
      "eventType": "ONSTAGE",
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Get ready to groove and move! Unleash your inner star with a solo dance extravaganza!",
      "rules": "# No usage of props is allowed for this round.\n# Participants will not be judged based on their costumes.\n# The soundtrack should be submitted in the respective google forms shared by the coordinators and to be brought in a pen drive (in .mp3 format only).\n# Any kind of fluid, flame, powders, glitters, heavy or sharp objects or any material which has the possibility of tampering/damaging the stage is STRICTLY not allowed.\n# Vulgarity and obscenity at any point are strictly not allowed. It can lead to immediate disqualification. Songs should be chosen accordingly.\n# Violation of any of the above rules will lead to heavy penalties.\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Time Limit: 5 minutes \n# Styles: All except Folk dance such as Garba, Bhangra, Bihu, etc.",
      "whatsappLink": "",
      "categories": "Dance,Non-Technical,Entertainment",
      "isRegOpen": true
    },
    {
      "id": 5,
      "name": "RESONANCE",
      "amount": 700,
      "shortDesc": "COUPLE DANCE",
      "eventType": "ONSTAGE",
      "teamSizeMin": 2,
      "teamSizeMax": 2,
      "desc": "Step into the rhythm,hand in hand-where friends and dance unite.",
      "rules": "# Participants can use more than one song in their performance.\n# The soundtrack should be submitted in the respective google forms shared by the coordinators and to be brought in a pen drive (in .mp3 format only).\n# Any kind of fluid, flame, powders, glitters, heavy or sharp objects or any material which has the possibility of tampering/damaging the stage are STRICTLY not allowed.\n# Vulgarity and obscenity at any point are strictly not allowed. It can lead to immediate disqualification. Songs should be chosen accordingly\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Time limit: 2-4 minutes ( +1 minute setup and clearance time).\n# Teams must perform any sequence of their choice on a song of their choice.",
      "whatsappLink": "https://chat.whatsapp.com/Hc97jx1cLo75mwgEN50y5m",
      "categories": "Dance,Non-Technical",
      "isRegOpen": true
    },
    {
      "id": 6,
      "name": "NRITYANJALI",
      "amount": 1000,
      "shortDesc": " GROUP DANCE",
      "eventType": "ONSTAGE",
      "teamSizeMin": 5,
      "teamSizeMax": 20,
      "desc": "Feel the beat, ignite the stage- group dance, where passion and talent collide.",
      "rules": "# Only one team per college is allowed to perform.\n# Participants can use more than one song in their performance.\n# The soundtrack should be submitted in the respective google forms shared by the coordinators and to be brought in a pen drive (in .mp3 format only).\n# Any kind of fluid, flame, powders, glitters, heavy or sharp objects or any material which has the possibility of tampering/damaging the stage are STRICTLY not allowed.\n# Vulgarity and obscenity at any point are strictly not allowed. It can lead to immediate disqualification. Songs should be chosen accordingly\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Time limit: 3- 5 minutes ( +1 minute setup and clearance time)\n# Teams must perform any sequence of their choice on a song of their choice.",
      "whatsappLink": "",
      "categories": "Dance,Non-Technical,Entertainment",
      "isRegOpen": true
    },
    {
      "id": 7,
      "name": "MR AND MISS FRESHERS",
      "shortDesc": "Mr & Ms Freshers",
      "eventType": "ONSTAGE",
      "amount": 450,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Dress to impress, ready to shine- Mr. and Miss Freshers, where stars align.",
      "rules": "# This event will consist of 2 rounds, the first round will be the talent display round\n# The second round will be a personality round where the participant would be asked a question or asked to speak about a topic for less than 2 minutes.\n# The soundtrack should be submitted in the respective google forms shared by the coordinators and to be brought in a pen drive (in .mp3 format only).\n# Incase of any technical issues, the participant would be allowed to perform the entire performance from the beginning.\n# Under no condition (other than technical issues) would the participant be allowed to stop and start the performance again.\n# The final scoring would be based on equal weightage of both the rounds.\n --Talent round: 50 points\n --Personality round: 50 points\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Rounds: 2 (Talent and Personality)\n# Time Limit: 2-3 Minutes for Talent Round and less than 2 minutes for Personality round.",
      "whatsappLink": "https://chat.whatsapp.com/HMmO0CVmkvSBabJM9GPEvC",
      "categories": "Fashion,Non-Technical",
      "isRegOpen": true
    },
    {
      "id": 8,
      "name": "HAUTE COUTURE",
      "shortDesc": "Fashion Show (Intra-University)",
      "eventType": "ONSTAGE",
      "amount": 450,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Unleash your inner fashioninsta, ignite the runway- Fashion show, where style reigns supreme.",
      "rules": "# Vulgarity and obscenity at any point are strictly not allowed. It can lead to immediate disqualification.\n# Use of cigarettes, alcohol and unfair means is strongly prohibited.\n# Tracks to be played in the background.\n# Incase of any technical issues, the participant would be allowed to perform the entire performance from the beginning.\n# Under no condition (other than technical issues) would the participant be allowed to stop and start the performance again.\n# The final scoring would be based on equal weightage of all the rounds.\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Rounds: 3 (Ethnic , Formal And Urban Wear).",
      "whatsappLink": "https://chat.whatsapp.com/HgkN26aKHU89kB6Aisopky",
      "categories": "Fashion,Non-Technical",
      "isRegOpen": true
    },
    {
      "id": 9,
      "name": "THREADMILL",
      "shortDesc": "Fashion Show (Inter-University)",
      "eventType": "ONSTAGE",
      "amount": 1000,
      "teamSizeMin": 5,
      "teamSizeMax": 20,
      "desc": "Where trends come alive, and style takes flights- Fashion show, a dazzling fashion delight.",
      "rules": "# Vulgarity and obscenity at any point are strictly not allowed. It can lead to immediate disqualification.\n# Use of cigarettes, alcohol and unfair means is strongly prohibited.\n# Tracks to be played in the background.\n# Incase of any technical issues, the participant would be allowed to perform the entire performance from the beginning.\n# Under no condition (other than technical issues) would the participant be allowed to stop and start the performance again.\n# The final scoring would be based on equal weightage of all the rounds.\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Rounds: 3 (Ethnic , Formal And Urban Wear).",
      "whatsappLink": "https://chat.whatsapp.com/HgkN26aKHU89kB6Aisopky",
      "categories": "Fashion,Non-Technical",
      "isRegOpen": true
    },
    {
      "id": 10,
      "name": "MUSCLE FIT",
      "shortDesc": "BODY-BUILDING",
      "eventType": "ONSTAGE",
      "amount": 350,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Transform your strenght, sculpt your physique- Bodybuilding, the ultimate peak.",
      "rules": "# Vulgarity and obscenity at any point are strictly not allowed. It can lead to immediate disqualification.\n# Use of cigarettes, alcohol and unfair means is strongly prohibited.\n# Tracks to be played in the background.\n# Incase of any technical issues, the participant would be allowed to perform the entire performance from the beginning.\n# Under no condition (other than technical issues) would the participant be allowed to stop and start the performance again.\n# The final scoring would be based on equal weightage of all the rounds.\n# Time limit should be strictly followed. Participants will be heavily penalized by judges for not doing so.\n# The decision of the organizers regarding the final line-up would be final.\n# Rounds: 3 (Ethnic , Formal And Urban Wear).",
      "whatsappLink": "",
      "categories": "Non-Technical",
      "isRegOpen": true
    },
    {
      "id": 11,
      "name": "basketball",
      "shortDesc": "basketball - ( 3v3 )",
      "eventType": "OFFSTAGE",
      "amount": 2000,
      "teamSizeMin": 4,
      "teamSizeMax": 4,
      "desc": "Team Size 4 ( 3 Main and 1 Substitute ) ",
      "rules": "#Judgment Criteria – fixture winner\n#Only five players per team on the court. \n#Score more than your opponent to win.\n#Score within the shot clock.\n#The offense has five seconds to inbound the ball. \n#Ball and ballhandler must remain inbounds.\n#You can't rest once the game started \n#You must dribble the ball while playing and should not carry the ball in hand.",
      "whatsappLink": "",
      "categories": "Sports",
      "isRegOpen": true
    },
    {
      "id": 12,
      "name": "basketball",
      "shortDesc": "basketball - Solo",
      "eventType": "OFFSTAGE",
      "amount": 100,
      "teamSizeMin": 4,
      "teamSizeMax": 4,
      "desc": "Basketball solo is a 3 point shooting Scoring by launching the ball from beyond the 3 pointer line",
      "rules": "#Judgment Criteria – fixture winner \n#Score more than your opponent to win.\n#Score within the shot clock.\n#The offense has five seconds to inbound the ball. \n#Ball and ballhandler must remain inbounds.\n#You can't rest once the game started \n#You must dribble the ball while playing and should not carry the ball in hand.",
      "whatsappLink": "",
      "categories": "Sports",
      "isRegOpen": true
    },
    {
      "id": 13,
      "name": "Beach Volleyball",
      "shortDesc": "Beach Volleyball",
      "eventType": "OFFSTAGE",
      "amount": 150,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Beach volleyball is a dynamic team sport played on sandy courts, where two teams of two players each aim to score points by sending the ball over the net and into the opponent's side of the court.",
      "rules": "#Don't Let the ball hit the floor on your side of the net\n#Three Contacts/Hits per Side\n#Total 4 players, two players on a team\n#No player can hit the ball twice in succession\n#A player may not cause the ball to come to a rest during contact\n#No part of a player’s body or uniform is allowed to touch the net\n#A match is won by whoever wins two sets.",
      "whatsappLink": "",
      "categories": "Sports",
      "isRegOpen": true
    },
    {
      "id": 14,
      "name": "Badminton",
      "shortDesc": "Badminton",
      "eventType": "OFFSTAGE",
      "amount": 200,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Badminton is a fast-paced racquet sport played on a rectangular court, where players use a shuttlecock to score points by hitting it over the net to the opponent's side",
      "rules": "The participant will get 2 Quarters for 10 min.\n#After 1st quarter there will be side change between participant.",
      "whatsappLink": "",
      "categories": "Sports",
      "isRegOpen": true
    },
    {
      "id": 15,
      "name": "Archery",
      "shortDesc": "Archery",
      "eventType": "OFFSTAGE",
      "amount": 0,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Archery is the skillful sport and practice of using a bow to shoot arrows at a target with precision and accuracy",
      "rules": "",
      "whatsappLink": "",
      "categories": "Sports",
      "isRegOpen": true
    },
    {
      "id": 16,
      "name": "Tug-Of-War",
      "shortDesc": "Tug-Of-War",
      "eventType": "OFFSTAGE",
      "amount": 500,
      "teamSizeMin": 5,
      "teamSizeMax": 5,
      "desc": "Tug of war is a competitive team sport in which two groups pull on opposite ends of a rope, aiming to move a marker in their direction..",
      "rules": "#There will be total 12 players. Each team will have 6 players.(can be changed according to the situation).\n#Once time started the players have to pull the rope on their respective sides.\n#Touching the ground for a longer period of time is considered as a foul.\n#Their is a particular technique that needs to         be applied while playing the game if not their will be a foul which can led to disqualification.\n#The red mark on the rope needs to be perpendicular angle to the centre point before the commencement of the game.\n#As soon as the second mark on the rope from centre crosses over the centre line the team to pull the rope wins the game.",
      "whatsappLink": "",
      "categories": "Sports",
      "isRegOpen": true
    },
    {
      "id": 17,
      "name": "Squat Competition",
      "shortDesc": "Squat Competition",
      "eventType": "OFFSTAGE",
      "amount": 150,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Squats game challenges players to perform squats within a set time frame, with each repetition contributing to their score or progress in the game",
      "rules": "#Whoever does more squats wins.\n#Players cant stop or rest in between once the game is started.\n#Players will be disqualified if their posture changes in between.",
      "whatsappLink": "",
      "categories": "Sports",
      "isRegOpen": true
       },
    {
      "id": 18,
      "name": "Push Ups",
      "shortDesc": "Push Ups",
      "eventType": "OFFSTAGE",
      "amount": 150,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Pushup game challenges players to perform pushups within a set time frame, with each repetition contributing to their score or progress in the game.",
      "rules": "#Whoever does more pushups wins.\n#Players cant stop or rest in between once the game is started.\n#Players will be disqualified if their posture changes in between.",
      "whatsappLink": "",
      "categories": "Sports",
      "isRegOpen": true
      },
      {
        "id": 19,
        "name": "Table Tennis",
        "shortDesc": "Table Tennis Solo",
        "eventType": "OFFSTAGE",
        "amount": 150,
        "teamSizeMin": 1,
        "teamSizeMax": 1,
        "desc": "Table tennis solo is a fast-paced indoor sport where players use small paddles to hit a lightweight ball over a net, aiming to score points by making the ball bounce on the opponent's side of the table",
        "rules": "#Games are played to 11 points.\n#Toss the ball straight up when serving.\n#Double serves must go right court to right court.\n#You may not touch the table with your non paddle hand.\n#The team winning a coin toss has the option of choosing:\n#The right to receive or serve first.\n#The right to require the losing team to make the first choice.\n#After choice A & B have been made, the other team makes the remaining choice.",
        "whatsappLink": "",
        "categories": "Sports",
        "isRegOpen": true
      },
      {
        "id": 20,
        "name": "Table Tennis",
        "shortDesc": "Table Tennis Duo",
        "eventType": "OFFSTAGE",
        "amount": 200,
        "teamSizeMin": 2,
        "teamSizeMax": 2,
        "desc": "Table tennis duo is a fast-paced indoor sport where players use small paddles to hit a lightweight ball over a net, aiming to score points by making the ball bounce on the opponent's side of the table",
        "rules": "#Games are played to 11 points.\n#Toss the ball straight up when serving.\n#Double serves must go right court to right court.\n#You may not touch the table with your non paddle hand.\n#The team winning a coin toss has the option of choosing:\n#The right to receive or serve first.\n#The right to require the losing team to make the first choice.\n#After choice A & B have been made, the other team makes the remaining choice.",
        "whatsappLink": "",
        "categories": "Sports",
        "isRegOpen": true
      },
    
    {
      "id": 21,
      "name": "BGMI",
      "shortDesc": "BGMI- Solo",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Gear up for intense battlegrounds in our BGMI Solo Competition! Prove your skills, outlast the competition, and emerge as the ultimate solo survivor.",
      "rules": "#We shall have moderators overseeing each match, so any attempt to cheat will lead to disqualification.\n#Any toxicity directed towards either one’s teammates or opponents will not be tolerated and can lead to disqualification according to moderators’ discretio.\n#Ensure that the details provided in the form are correct, including case sensitivity in one’s Riot IDs. Outliers will be kicked from the tournament.\n#All arrangements regarding network connection and gaming hardware would be the sole responsibility of the  participants.\n#Any requests for match pause other than timeout (e.g., due to afk teammates) may or may not be entertained at moderators’ discretion and may even lead to the continuation of unbalanced matches (e.g., 4v5).\n#After 5 mins of scheduled match time, if all five team players cannot show up in the moderator’s lobby, then a loss would be considered for that team in the match. \n#Any last minute player addition will lead to team disqualification.\n#A friend request and match invite will be sent to the participants on the Discord server 10 minutes prior to the scheduled match time.\n#Each team has one timeout for each half (i.e., two timeouts for the match); it can be accessed in the Esc menu near the surrender button. Once activated, it will take voting like a surrender vote but for a timeout. Each timeout is 1 minute long.\n#All Qualifiers matches will be knockouts. There would be 8 groups with 8 teams in each. The winning team of each qualifier group will advance to finals.\n#Finals will be of 8 teams with Double Elimination Bracket.\n#Maps would be decided by toss and map ban procedure.\n#The procedure includes the toss-winning captain banning a particular map which his team does not wish to play, followed by the other team captain banning another map; alternate cycles of this would leave a single map to play.\n#The qualifiers and earlier stages of finals would be single map matches. The last three matches of the finals would be in the best-of -3 format",
      "whatsappLink": "",
      "categories": "Esports,Technical",
      "isRegOpen": true
    },
    {
      "id": 22,
      "name": "BGMI",
      "shortDesc": "BGMI- Squad",
      "eventType": "OFFSTAGE",
      "amount": 200,
      "teamSizeMin": 1,
      "teamSizeMax": 4,
      "desc": "Get your squad ready for action in our BGMI Squad Competition! Team up, strategize, and conquer the battlefield in a test of teamwork and gaming prowess.",
      "rules": "#We shall have moderators overseeing each match, so any attempt to cheat will lead to disqualification.\n#Any toxicity directed towards either one’s teammates or opponents will not be tolerated and can lead to disqualification according to moderators’ discretio.\n#Ensure that the details provided in the form are correct, including case sensitivity in one’s Riot IDs. Outliers will be kicked from the tournament.\n#All arrangements regarding network connection and gaming hardware would be the sole responsibility of the  participants.\n#Any requests for match pause other than timeout (e.g., due to afk teammates) may or may not be entertained at moderators’ discretion and may even lead to the continuation of unbalanced matches (e.g., 4v5).\n#After 5 mins of scheduled match time, if all five team players cannot show up in the moderator’s lobby, then a loss would be considered for that team in the match. \n#Any last minute player addition will lead to team disqualification.\n#A friend request and match invite will be sent to the participants on the Discord server 10 minutes prior to the scheduled match time.\n#Each team has one timeout for each half (i.e., two timeouts for the match); it can be accessed in the Esc menu near the surrender button. Once activated, it will take voting like a surrender vote but for a timeout. Each timeout is 1 minute long.\n#All Qualifiers matches will be knockouts. There would be 8 groups with 8 teams in each. The winning team of each qualifier group will advance to finals.\n#Finals will be of 8 teams with Double Elimination Bracket.\n#Maps would be decided by toss and map ban procedure.\n#The procedure includes the toss-winning captain banning a particular map which his team does not wish to play, followed by the other team captain banning another map; alternate cycles of this would leave a single map to play.\n#The qualifiers and earlier stages of finals would be single map matches. The last three matches of the finals would be in the best-of -3 format",
      "whatsappLink": "",
      "categories": "Esports,Technical",
      "isRegOpen": true
    },
    {
      "id": 23,
      "name": "COD-Solo",
      "shortDesc": "Esports",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Enter the combat zone of our COD Solo Competition! It's a test of your individual skills, strategy, and reflexes in a high-stakes battle for supremacy.",
      "rules": "#By participating in our tournaments, all participants automatically agree that they vow to respect fellow participants.\n#Do not join an official tournament lobby if you are not part of the team that is playing. Ineligible players that do join are at risk of being banned from the tournament or receive other penalties.\n#The usage of ‘jailbroken’ or ‘rooted’ devices in tournament matches is not permitted.\n#We reserve the right to edit the rules at any time and disqualify teams for reasons not stated in this list or take other action.\n#Teams that have no representative in the chat after the tournament has started may be disqualified.\n#It is prohibited to spam or use offensive messages on any of the on-going events of Momentum & The NorthCap University and doing so may result in us taking punitive measures against you.\n#There will be 2 rounds.\n--Round 1 : 1 match will be played amongst the players in the lobby, top 20% qualify for the next round.\n--Round 2 : 1 matches will be played amongst the Qualifiers from the first round.\n#Top 3 players from Round 2 will be rewarded.\n#Participation certificates for all the Participants.",
      "whatsappLink": "",
      "categories": "Esports,Technical",
      "isRegOpen": true
    },
    {
      "id": 24,
      "name": "Valorant",
      "shortDesc": "Esports",
      "eventType": "OFFSTAGE",
      "amount": 200,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Welcome to the world of tactical precision in our Valorant Competition. Teams face off in strategic showdowns, aiming for victory through sharp aim and coordinated gameplay.",
      "rules": "#We shall have moderators overseeing each match, so any attempt to cheat will lead to disqualification.\n#Any toxicity directed towards either one’s teammates or opponents will not be tolerated and can lead to disqualification according to moderators’ discretio.\n#Ensure that the details provided in the form are correct, including case sensitivity in one’s Riot IDs. Outliers will be kicked from the tournament.\n#All arrangements regarding network connection and gaming hardware would be the sole responsibility of the  participants.\n#Any requests for match pause other than timeout (e.g., due to afk teammates) may or may not be entertained at moderators’ discretion and may even lead to the continuation of unbalanced matches (e.g., 4v5).\n#After 5 mins of scheduled match time, if all five team players cannot show up in the moderator’s lobby, then a loss would be considered for that team in the match. \n#Any last minute player addition will lead to team disqualification.\n#A friend request and match invite will be sent to the participants on the Discord server 10 minutes prior to the scheduled match time.\n#Each team has one timeout for each half (i.e., two timeouts for the match); it can be accessed in the Esc menu near the surrender button. Once activated, it will take voting like a surrender vote but for a timeout. Each timeout is 1 minute long.\n#All Qualifiers matches will be knockouts. There would be 8 groups with 8 teams in each. The winning team of each qualifier group will advance to finals.\n#Finals will be of 8 teams with Double Elimination Bracket.\n#Maps would be decided by toss and map ban procedure.\n#The procedure includes the toss-winning captain banning a particular map which his team does not wish to play, followed by the other team captain banning another map; alternate cycles of this would leave a single map to play.\n#The qualifiers and earlier stages of finals would be single map matches. The last three matches of the finals would be in the best-of -3 format",
      "whatsappLink": "",
      "categories": "Esports,Technical",
      "isRegOpen": true
    },
    {
      "id": 25,
      "name": "Clash Royale",
      "shortDesc": "Esports",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Get ready to clash in our Royale Competition! Build decks, strategize, and duel in a fast-paced showdown to see who will reign supreme in the arena.",
      "rules": "#Player registration is necessary in the form\n#THE PLAYERS MUST JOIN OUR DISCORD SERVER DURING THE TOURNAMENT, AS ALL THE LOGISTICAL INFORMATION WILL BE SHARED THERE ONLY.\n#It is a standard 1v1 overtime-enabled match.\n#We shall have moderators overseeing each match, so any attempt to cheat will lead to disqualification.\n#Ensure that the details provided in the form are correct, including case sensitivity in one’s Player Tag. Outliers will be kicked from the tournament.\n#All arrangements regarding network connection and gaming hardware would be the sole responsibility of the  participants.\n#A tournament will be created and the tournament name and password will be sent to the participants on the Discord server 10 minutes prior to the scheduled match time.\n#Random opponents will be selected from the participants for 1v1 rounds.\n#Winner will be decided based on the total number of wins in the tournament.\n#Maximum 3 losses will be allowed per participant.\n#The top 3 players will be rewarded.\n#Participation certificates for all the participants.",
      "whatsappLink": "",
      "categories": "Esports,Technical",
      "isRegOpen": true
    },
    {
      "id": 26,
      "name": "GameZone",
      "shortDesc": "GameZone(3)",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Welcome to our GAMEZONE, where a variety of gaming talents unite. From FPS to strategy, join us for an epic showdown of diverse gaming skills.",
      "rules": "The usage of jailbreak devices in tournament matches is not permitted.\n#teams should have a representative otherwise will be disqualified",
      "whatsappLink": "",
      "categories": "Non-Technical, Literature",
      "isRegOpen": true
    },
    {
      "id": 27,
      "name": "Words Worth",
      "shortDesc": "crossword competition",
      "eventType": "OFFSTAGE",
      "amount": 100,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Spelling Bee is a word puzzle game that challenges players to form words using a set of seven letters. The objective is to create as many words as possible, with extra points awarded for using all seven letters in a word.",
      "rules": "The speller listens carefully to the pronouncer and asks for the word to be repeated if necessary.\n#The judge(s) determines whether or not the word was spelled correctly. If the spelling is incorrect, that speller is eliminated from the game.",
      "whatsappLink": "",
      "categories": "Non-Technical, Literature",
      "isRegOpen": true
    },
    {
      "id": 28,
      "name": "Chitra Katha",
      "shortDesc": "drawing competition",
      "eventType": "OFFSTAGE",
      "amount": 100,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc":"In this online competition ,themes will be given, Participants needs to select one among them and make painting/art on that particular theme. Major marks will be awarded to Innovative ideas and presentation of the painting/art",
      "rules": " All the participants will be assigned a designated work area·\n# Participants will have a specific amount of time to complete their artwork on the event day.\n#·Participants are responsible for bringing their art supplies, including canvas, brushes, paints, and any other required materials.",
      "whatsappLink": "",
      "categories": "Non-Technical, Creative",
      "isRegOpen": true
    },
    {
      "id": 29,
      "name": "Hand Painting",
      "shortDesc": "Hand Painting",
      "eventType": "OFFSTAGE",
      "amount": 150,
      "teamSizeMin": 1,
      "teamSizeMax": 2,
      "desc": "a unique drawing, painting and art competition designed to encourage creative expression",
      "rules": "#Judgment criteria:\n#Originality : Is the design fresh, new, different or has this design, or something very similar to it, been done often by others?\n#Creativity: Is the design artistic and creative?\n#Difficulty of Design: \n#THEME- Distortion Work\n\n#Rules:\n#Each competitor must supply all of his or her own hand painting supplies including paints, brushes, rinse water for brushes, water container, sponges, sponge-tipped applicators and other tools and supplies necessary to complete the task.\n#Competitors may not share paints or other supplies during competition.\n#Models will be the responsibility of the competitor.\n#Competitors may not use photos or drawings to refer to while painting.\n#All designs will be painted free-hand.\n#On the spot entries will not be entertained and prior registrations are compulsory.\n#Reproduction of existing ideas or designs will lead to disqualification.\n#The last date for registration is insert date.\n#Competitors are encouraged to become familiar with the rules well in advance of the competition. Failure to comply with these rules may result in point reduction or complete disqualification from the competition.",
      "whatsappLink": "",
      "categories": "creative, Fun Activity",
      "isRegOpen": true
    },
    {
      "id": 30,
      "name": "Wall Painting",
      "shortDesc": "Wall Painting",
      "eventType": "OFFSTAGE",
      "amount": 400,
      "teamSizeMin": 1,
      "teamSizeMax": 4,
      "desc": "Welcome to our Wall Painting Competition, where artists transform blank walls into vibrant canvases, weaving stories and igniting creativity.",
      "rules": "#Judgment Criteria – Originality : Is the design fresh, new, different or has this design, or something very similar to it, been done often by others? Creativity: Is the design artistic and creative?Difficulty of Design#Theme- Frontlines #Each competitor must supply all of his or her own painting supplies including paints, brushes, rinse water for brushes, water container, sponges, sponge-tipped applicators and other tools and supplies necessary to complete the task.\n#Competitors may not share paints or other supplies during competition.\n#Competitors may not use photos or drawings to refer to while painting.\n#All designs will be painted free-hand.\n#Competitors are encouraged to become familiar with the rules well in advance of the Competition. \n#Failure to comply with these rules may result in point reduction or complete disqualification from the competition.",
      "whatsappLink": "",
      "categories": "creative, Fun Activity",
      "isRegOpen": true
    },
    {
      "id": 31,
      "name": "Scavenger Hunt",
      "shortDesc": "Scavenger Hunt",
      "eventType": "OFFSTAGE",
      "amount": 250,
      "teamSizeMin": 1,
      "teamSizeMax": 4,
      "desc": "Get ready for an exhilarating adventure! Our Scavenger Hunt Competition invites you to decode clues, solve puzzles, and explore as you race against the clock in a quest for hidden treasures.",
      "rules":"Teams that do not return to the starting point within the allotted time will be eliminated from the game.\n# Teams that fail to complete a specified number of tasks within the time limit may be eliminated",
      "whatsappLink": "",
      "categories": "Fun Activities,Non-Technical",
      "isRegOpen": true
    },
    {
      "id": 32,
      "name": "Photo Competition",
      "shortDesc": "Photo Competition",
      "eventType": "OFFSTAGE",
      "amount": 100,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Capturing moments and emotions frozen in time, our Photo Competition brings together photographers to showcase their unique perspectives and tell compelling visual stories.",
      "rules": "#Judgment Criteria- Best photos will be selected on the basis of their Composition and subject.\n#Theme: Exposure Bracketing\nDescription: \n#Particular theme for photography will be given to the contestants. \n#Theme of the event is “Exposure Bracketing” \n#Exposure bracketing is a technique where, instead of taking a single photo, you take three (or more) that are all exposed slightly differently; normally one is correctly exposed, one slightly underexposed, and one slightly overexposed.\n#If you shoot bracketed shots,you can blend different parts of the image yourself if you need to, and, if something is moving through the scene, you can replace it with original image data instead of relying on Photoshop’s tools.\nRules:\n#The photographs must be in accordance with the theme.\n#The photographs can be taken with any camera,i.e. DSLR,Digital camera or phone cameras\n#The photographs can be Portrait or Landscape.\n#Photographs must be original without any copyright or watermark sign.\n#Photographs should be a minimum 1MB in size.\n#Photo enhancement is allowed, but you are not allowed to manipulate the content. \n#Best photos will be selected on the basis of their Composition and subject.",
      "whatsappLink": "",
      "categories": "Creative",
      "isRegOpen": true
    },
    {
      "id": 33,
      "name": "Bollywood Quiz",
      "shortDesc": "Bollywood Quiz",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "STEP INTO THE GLITZY WORLD OF BOLYWOOD QUIZ AND TEST YOU KNOWLEDGE OF INDIA'S CINEMATIC ARTIST LEGENDS, FROM ICONIC TO MEMORABLE MARVELS",
      "rules": "#There will be 3 rounds for the quiz \n#The participants will be shortlisted after each round \n#Difficulty level will increase after each round \n#Stage one will consist of instrumental and dialogues and the name of the movie or song has to be guessed based on the question. \n#Stage two will consist of some famous pictures from a movie or hook steps of songs and the answers have to be guessed accordingly.\n#Round 2 will consist of some emojis and the song or movie name has to be guessed as the question says. \n#Third round will take hold of some Hindi song lyrics translated in English and the original song needs to be guessed. \n#Any number of individual students are welcome to participate in the quiz \n#Every question has a time limit \n#A chance of getting one wrong question right will be provided \n#Audio or video recordings can be played only twice whereas in an image question, the image will be shown the whole time. \n#The entire event is being organized on a digital platform. \n#The participants agree that the organizers would in no way be responsible for the internet connectivity that is required at all stages of the quiz. It is the sole responsibility of the participant to equip themselves with robust internet facilities to take part in this event. \n#If any participant is found to be using unfair means to win, the organizers hold the right to disqualify the participant at any stage of the event.",
      "whatsappLink": "",
      "categories": "Quizzing, Fun Activities",
      "isRegOpen": true
    },
    {
      "id": 34,
      "name": "Flameless Cooking",
      "shortDesc": "Flameless Cooking",
      "eventType": "OFFSTAGE",
      "amount": 200,
      "teamSizeMin": 1,
      "teamSizeMax": 2,
      "desc": "Fireless cooking, also known as no-cook or raw cooking, is a culinary technique that involves preparing dishes without the use of heat. This method, which has been practiced since ancient times, is gaining popularity due to its health benefits and environmental sustainability.",
      "rules": "#Judgment Criteria –\n#1.Nutritional value of the ingredients used.\n#2. Adherence to time limit\n#3. Low waste, clean and neat method of working.\n#4. Creativity,Innovativeness, presentation and confidence in narration.\n#5. Taste of dish presented.\n\n#Rules:\n#Participants should not bring any pre-cooked items\n#Pre-registrations are mandatory\n#Two members should be in a team to participate in the event.\n#Participants are supposed to display a chart having the name, ingredients and calorie count of each dish they have prepared.\n#All the items required for cooking should be brought by the participants themselves, including water, Only a working table will be provided.\n#Dishes should be purely vegetarian. \n#Participants should not bring any cut, chopped or grated raw materials. They should process it on the spot within allotted time.\n#Participants can bring non-electric equipment like mixer, chopper, juicer, grater etc.\n#The evaluation will be based on the taste of the dish, nutritional level, cleanliness and presentation, unique name of the dish and hygiene.",
      "whatsappLink": "",
      "categories": "Culinary, Creative",
      "isRegOpen": true
    },
    {
      "id": 35,
      "name": "Reel Making Competition",
      "shortDesc": "Reel Making Competition",
      "eventType": "OFFSTAGE",
      "amount": 150,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Welcome to the Reel Making Competition, where filmmakers harness creativity and storytelling prowess to craft compelling short films, taking us on unforgettable cinematic journeys.",
      "rules": "#All entries must be original creations. Plagiarism or unauthorized use of copyrighted material is strictly prohibited.·\n# Participants are required to upload their reels to their YouTube channels.",
      "whatsappLink": "",
      "categories": "Creative,Non-Technical",
      "isRegOpen": true
    },
    {
      "id": 36,
      "name": "Brain Studio",
      "shortDesc": "Brain Studio",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Join the Brain Studio Competition, where intellect meets innovation. Sharpen your mind, solve challenges, and compete in an arena of cognitive prowess.",
      "rules": "#Judgment Criteria –The competitor who solves the cube in the fastest time will win the level.\n#There will be 4 locked wires containing code. (Each wire containing 1 code of   3/4digits)\n3Participants need to select the right key of the lock.\n#Code will be accessible only after opening the lock.\n#Open the box from the 4-code given in round 1 without seeing.\n#Inside the box 2 cubes (Rubik’s, mirror) will be there.\n#Need to solve both of them. \n \n#Participants with less time span will be the winner.\n#Every round has to solved in a given amount of time otherwise negative points will be given for each round.",
      "whatsappLink": "",
      "categories": "Quizzing,Fun Activities",
      "isRegOpen": true
    },
    {
      "id": 37,
      "name": "Best Out Of Waste",
      "shortDesc": "Best Out Of Waste",
      "eventType": "OFFSTAGE",
      "amount": 100,
      "teamSizeMin": 1,
      "teamSizeMax": 2,
      "desc": "Embrace sustainability and creativity in our Best Out of Waste Competition. Watch as discarded items are transformed into art, showcasing the power of recycling and imagination.",
      "rules": "Participants are expected to follow safety precautions when handling tools or potentially hazardous waste materials.\n#After the event, participants are encouraged to responsibly dispose of or recycle their projects to minimize waste",
      "whatsappLink": "",
      "categories": "Non-Technical, Creative",
      "isRegOpen": true
    },
    {
      "id": 38,
      "name": "IPL Auction",
      "shortDesc": "IPL Auction",
      "eventType": "OFFSTAGE",
      "amount": 150,
      "teamSizeMin":1,
      "teamSizeMax":1,
      "desc": "The IPL Auction is a group event consisting of 2 team members. This event involves cricket quiz, team bidding of IPL Teams and real life experience of Player Auction with virtual money. A chance for participants to have a feel of becoming Owners of IPL Teams",
      "rules": "#In Round-1 each member should answer a set of questions that are related to IPL cricket matches & players. Top 10 Teams in Round-1 are selected for Round-2 of IPL Auction\n\n\n#The selected teams in Round-1 will be given the names of 8 IPL teams and virtual money using which they can buy players in the auction. \n#Every team will get a certain fixed amount of virtual money to bid in the Auctions.\n#Players will be sold to the team with the highest bidding.\n#Every team should have exactly 11 players in their team (4 BATSMEN,4 BOWLERS, 3 ALL-ROUNDERS).\n#No team can have more than 11 players. 3 players(ONE ALL-ROUNDER, ONE BATSMEN, ONE BOWLER) will be fixed and held in every team so as to give a strong base to your team.\n#Every player in the Auction will be having a certain skill points so as to give you a clarification of the player in their respective field.\nSkill points of the players will be calculated on their past 2 year performance.\n#Winner will be decided on the basis of the combination of their team and the utilization of the money on the players.\n#Whosoever will bid the highest will get the player and there will be no backing out if you bid the highest.\n#Any team violating these rules might get penalized and might be disqualified from the Auction 2022.\n#Each team should register with a team name.\n#The minimum number of participants in a team should be 3 and not exceed 5.\n#Each team should have a team leader and only he is allowed to take the quiz.\n#The top 10 Teams in Round-1 are selected for Round-2 of the IPL Auction.\n#Teams selected for round 2 should be present in university for offline bidding process\n#Each team can bring their own calculator, pen and sheets to record their team’s progress.",
      "whatsappLink": "",
      "categories": "Quizzing, Esports, Finance",
      "isRegOpen": true
    },
    {
      "id": 39 ,
      "name": "Typreracer",
      "shortDesc": "Typeracer",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Typeracer tests are straightforward to use. You visit an online typing test tool, select a test, and start typing the provided text. As you type, the tool records your keystrokes and calculates your WPM and accuracy based on the number of correct words typed within a specified time frame.",
      "rules": "#Use of editing tools for correcting the mistakes in typed matter is strictly prohibited.\n# Any auto type tool should not be used.\n#Participation certificates for all the participants.",
      "whatsappLink": "",
      "categories": "Technical,Fun Activities",
      "isRegOpen": true
    },
    {
      "id": 40,
      "name": "Digital Graphics",
      "shortDesc": "Digital graphics",
      "eventType": "OFFSTAGE",
      "amount": 100,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "The aim of the Digital Graphics is not just to judge the students based on their creative aspects but also to trigger thought process among the students",
      "rules": "#Any artwork on the poster must be original in design. \n#Poster designs containing clip art and downloaded brushes will not be considered by the judges.\n#The poster must be related to the given theme.\n#Contestants will be given 2 hours to complete the design.",
      "whatsappLink": "",
      "categories": "Creative",
      "isRegOpen": true
    },
    {
      "id": 41,
      "name": "T-shirt designing",
      "shortDesc": "T-shirt designing",
      "eventType": "OFFSTAGE",
      "amount": 150,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "If you have an awesome idea for a t-shirt design, submit it here. It could end up on a customized art product that people all around the world can buy!",
      "rules": "#Participants are required install  the necessary design software installed (Bewakoof App).\n# Participants will have a set amount of time to complete their T-shirt design using the designated software (Bewakoof App). ",
      "whatsappLink": "",
      "categories": "Creative",
      "isRegOpen": true
    },
    {
      "id": 42,
      "name": "Stock Market",
      "shortDesc": "Stock Market",
      "eventType": "OFFSTAGE",
      "amount": 200,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "The Mock Stock Challenge is governed by game rules that you should be aware of to ensure you fully understand the online trading process and to make the most from this experience and possibly win it!",
      "rules": " Any violation of the rules of the given at the start day may result in the invalidation of a transaction. Repeated violation of the rules may result in the disqualification of a team.",
      "whatsappLink": "",
      "categories": "Finance,Technical",
      "isRegOpen": true
    },
    {
      "id": 43,
      "name": "B-Bizz",
      "shortDesc": "B-Bizz",
      "eventType": "OFFSTAGE",
      "amount": 200,
      "teamSizeMin": 1,
      "teamSizeMax": 2,
      "desc": "B-Bizz focuses on providing an overview of E-Business. The participants will have to create their own idea on the product or service which they desire. The Participants will have to make a Business Plan on their product or service.",
      "rules": "#Idea should be unique \n#No existing product should be listed·\n # It is prohibited to spam or use offensive messages on any of the on-going events",
      "whatsappLink": "",
      "categories": "E-business,Finance,Technical",
      "isRegOpen": true
    },
    {
      "id": 44,
      "name": "Application Bbiz",
      "shortDesc": "Application Bbiz",
      "eventType": "OFFSTAGE",
      "amount": 200,
      "teamSizeMin": 1,
      "teamSizeMax": 2,
      "desc": "This competition invites all budding app developers to come together and create innovative solutions that address environmental, social, or economic challenges, with a strong focus on sustainability.",
      "rules": "#All app submissions must be original and Plagiarism should be avoided.\n#Apps will be evaluated based on their relevance to sustainability, creativity, usability, technical proficiency, and the potential for positive impact.",
      "whatsappLink": "",
      "categories": "Problem solving,Finance,Technical",
      "isRegOpen": true
    },
    {
      "id": 45,
      "name": "IT QUIZ",
      "shortDesc": "IT QUIZ",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "The quiz can be described as a type of game where competitors try their best to answer the questions in less time. The quiz is not about random topics, it’s about specific topics.",
      "rules": "#The entire event is being organized on a digital platform. The participants agree that the organizers would in no way be responsible for the internet connectivity that is required at all stages of the quiz. It is the sole responsibility of the participant to equip themselves with robust internet facilities to take part in this event.\n# If any participant is found to be using unfair means to win, the organizers hold the right to disqualify the entire team at any stage of the event.\n\n#A participant can use personal Laptop / Mobiles for the Quiz\n# There will be 3 rounds for the quiz\n#The participants will be shortlisted after each round\n# Difficulty level will increase after each round",
      "whatsappLink": "",
      "categories": "Technical,Quizzing",
      "isRegOpen": true
    },
    {
      "id": 46,
      "name": "Puzzle Odessey",
      "shortDesc": "Puzzle Odessey",
      "eventType": "OFFSTAGE",
      "amount": 400,
      "teamSizeMin": 4,
      "teamSizeMax": 4,
      "desc": "",
      "rules": "",
      "whatsappLink": "",
      "categories": "",
      "isRegOpen": true
    },
    {
      "id": 47,
      "name": "Pictofusion",
      "shortDesc": "PictoFusion: Where Art Meets Pop Culture",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin":2,
      "teamSizeMax": 4,
      "desc": "Are you ready to put your artistic skills and quick thinking to the test? Look no further than the ultimate game of guessing and drawing in the form of an exciting Pictionary Event. The event will have different categories ranging from Literature to movies, music, and famous personalities to add a diverse dimension. It's time to pick up that marker, let your imagination run wild, and join in on the fun!",
      "rules": "",
      "whatsappLink": "",
      "categories": "",
      "isRegOpen": true
    },
    {
      "id": 48,
      "name": "Through The Lens",
      "shortDesc": "Through The Lens",
      "eventType": "OFFSTAGE",
      "amount": 100,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "A photography event, where students will have the chance to capture the breathtaking beauty of our campus festivities through their lenses. Whether it's the vibrant cultural performances, spirited competitions, or candid moments of camaraderie, this event is your opportunity to freeze-frame the magic of 'Momentum' for years to come. Bring your creativity and passion for photography, and let's make memories worth framing!",
      "rules": "",
      "whatsappLink": "",
      "categories": "",
      "isRegOpen": true
    },
    {
      "id": 49,
      "name": "EcoBrain",
      "shortDesc": "EcoBrain",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "Welcome, to EcoBrain Challenge, to the Sustainability Showdown! Get ready to flex your green knowledge in a crossword puzzle and test your quick thinking in rapid-fire questions, all in the name of a greener planet!",
      "rules": "",
      "whatsappLink": "",
      "categories": "",
      "isRegOpen": true
    },
    {
      "id": 50,
      "name": "MAD-AD",
      "shortDesc": "MAD-AD",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 2,
      "desc": "Welcome to the Mad Ad Competition, where creativity knows no bounds! Unleash your wackiest ideas and craft unforgettable advertisements in this thrilling challenge",
      "rules": "",
      "whatsappLink": "",
      "categories": "",
      "isRegOpen": true
    },
    {
      "id": 51,
      "name": "Photobooth",
      "shortDesc": "Photobooth",
      "eventType": "OFFSTAGE",
      "amount": 80,
      "teamSizeMin": 1,
      "teamSizeMax": 1,
      "desc": "",
      "rules": "",
      "whatsappLink": "",
      "categories": "",
      "isRegOpen": true
    }
  ]
  
  // Update cache
  cache = eventList;
  cacheTime = Date.now();

  return eventList;
};

const getEventById = async (eventId) => {
  const eventList = await getEvents();
  const event = eventList.find((e) => e.id == eventId);
  return event ? event : null;
};

export { getEvents, getEventById };
