import "../styles/globals.css";
import icon from "../public/M_logo_white.png";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
// import "../scss/style.scss";

function MyApp({ Component, pageProps, session }) {
  useEffect(() => {
    AOS.init({
      easing: "ease-out-cubic",
      once: true,
      offset: 50,
    });
  }, []);
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Momentum 2023</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={icon.src} />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </Head>
      <div data-theme="dark">
        <Navbar />
        <Component {...pageProps} />
        <Footer />
      </div>
    </SessionProvider>
  );
}

export default MyApp;
