name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

  build-prod:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image 
      run: docker build . --file Dockerfile --tag my-nextjs-docker
    - name: Export Docker Image
      run : |
            mkdir dimg
            docker save -o ./dimg/my-nextjs-docker-$(date +%s).tar my-nextjs-docker:latest
            
    - name: Send Image To Node 01
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
            username: 'ubuntu'
            server: 'momentum.ncuindia.edu'
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_PROD }} 
            local_path: './dimg/*'
            remote_path: '/home/ubuntu/dimg'
            sftpArgs: '-o ConnectTimeout=5'
             
    - name: Deploy on Node 01
      uses: appleboy/ssh-action@master
      with:
        host: 'momentum.ncuindia.edu'
        username: 'ubuntu'
        key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
        port: '22'
        script: |
                sudo docker load -i /home/ubuntu/dimg/$(ls -t /home/ubuntu/dimg | head -1)
                cd /home/ubuntu/services/nextapp/
                sudo docker compose down
                sudo docker compose up -d
